version: '3.4'

services:
  mcommerce.catalog.api.db:
    image: mongo

  mcommerce.catalog.api:
    image: ${DOCKER_REGISTRY-}mcommercecatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/MCommerce.Catalog.API/Dockerfile

  mcommerce.basket.api:
    image: ${DOCKER_REGISTRY-}mcommercebasketapi
    build:
      context: .
      dockerfile: Services/Basket/MCommerce.Basket.API/Dockerfile

  mcommerce.basket.api.db:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

volumes:
  mongo_data:
  portainer_data:
